// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: (msg: string) => __TAURI_INVOKE<string>("ping", { msg }),
	getSystemInfo: () => typedError<SystemInfo, AppError>(__TAURI_INVOKE("get_system_info")),
	getRepoHeadInfo: (repoPath: string) => typedError<RepoHeadInfo, AppError>(__TAURI_INVOKE("get_repo_head_info", { repoPath })),
	simulateRepoChange: (repoPath: string) => typedError<null, AppError>(__TAURI_INVOKE("simulate_repo_change", { repoPath })),
	openRepository: (path: string) => typedError<RepoSummary, AppError>(__TAURI_INVOKE("open_repository", { path })),
	closeRepository: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("close_repository", { path })),
	getOpenRepositories: () => typedError<RepoSummary[], AppError>(__TAURI_INVOKE("get_open_repositories")),
	getRecentRepos: () => typedError<RecentRepoEntry[], AppError>(__TAURI_INVOKE("get_recent_repos")).then((v) => ((v.status === "ok" ? { ...v, data: v.data.map(i=>i) } : v) as typeof v)),
	clearRecentRepos: () => typedError<null, AppError>(__TAURI_INVOKE("clear_recent_repos")),
	removeRecentRepo: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_recent_repo", { path })),
	selectRepoFolder: () => typedError<string | null, AppError>(__TAURI_INVOKE("select_repo_folder")),
	getBranches: (repoPath: string) => typedError<BranchListResult, AppError>(__TAURI_INVOKE("get_branches", { repoPath })),
	getCommitGraph: (repoPath: string, offset: number, limit: number) => typedError<CommitGraphPage, AppError>(__TAURI_INVOKE("get_commit_graph", { repoPath, offset, limit })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,commits:v.data.commits.map(i=>i)}) } : v) as typeof v)),
	getCommitDetails: (repoPath: string, commitId: string) => typedError<CommitDetails_Serialize, AppError>(__TAURI_INVOKE("get_commit_details", { repoPath, commitId })),
	getCommitFileDiff: (repoPath: string, commitId: string, filePath: string, ignoreWhitespace: boolean | null) => typedError<FileDiffResult, AppError>(__TAURI_INVOKE("get_commit_file_diff", { repoPath, commitId, filePath, ignoreWhitespace })),
	getRepoStatus: (repoPath: string) => typedError<RepoStatusResult, AppError>(__TAURI_INVOKE("get_repo_status", { repoPath })),
	getWorkingFileDiff: (repoPath: string, filePath: string, isStaged: boolean, ignoreWhitespace: boolean | null) => typedError<FileDiffResult, AppError>(__TAURI_INVOKE("get_working_file_diff", { repoPath, filePath, isStaged, ignoreWhitespace })),
	stageFile: (repoPath: string, filePath: string) => typedError<null, AppError>(__TAURI_INVOKE("stage_file", { repoPath, filePath })),
	unstageFile: (repoPath: string, filePath: string) => typedError<null, AppError>(__TAURI_INVOKE("unstage_file", { repoPath, filePath })),
	stageAll: (repoPath: string) => typedError<null, AppError>(__TAURI_INVOKE("stage_all", { repoPath })),
	unstageAll: (repoPath: string) => typedError<null, AppError>(__TAURI_INVOKE("unstage_all", { repoPath })),
	discardFileChanges: (repoPath: string, filePath: string) => typedError<string, AppError>(__TAURI_INVOKE("discard_file_changes", { repoPath, filePath })),
	restoreDiscard: (repoPath: string, token: string) => typedError<null, AppError>(__TAURI_INVOKE("restore_discard", { repoPath, token })),
	stageHunk: (repoPath: string, filePath: string, hunkIndex: number, isStaged: boolean) => typedError<null, AppError>(__TAURI_INVOKE("stage_hunk", { repoPath, filePath, hunkIndex, isStaged })),
	stageLines: (repoPath: string, filePath: string, hunkIndex: number, lineIndices: number[], isStaged: boolean) => typedError<null, AppError>(__TAURI_INVOKE("stage_lines", { repoPath, filePath, hunkIndex, lineIndices, isStaged })),
	createCommit: (repoPath: string, summary: string, description: string | null, amend: boolean | null) => typedError<CommitDetails_Serialize, AppError>(__TAURI_INVOKE("create_commit", { repoPath, summary, description, amend })),
	createBranch: (repoPath: string, name: string, targetCommit: string | null, checkout: boolean | null) => typedError<null, AppError>(__TAURI_INVOKE("create_branch", { repoPath, name, targetCommit, checkout })),
	checkoutBranch: (repoPath: string, branchName: string) => typedError<null, AppError>(__TAURI_INVOKE("checkout_branch", { repoPath, branchName })),
	renameBranch: (repoPath: string, oldName: string, newName: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_branch", { repoPath, oldName, newName })),
	deleteBranch: (repoPath: string, branchName: string, force: boolean | null) => typedError<string, AppError>(__TAURI_INVOKE("delete_branch", { repoPath, branchName, force })),
	fetchRepo: (repoPath: string, remote: string | null, prune: boolean | null, taskId: string | null) => typedError<string, AppError>(__TAURI_INVOKE("fetch_repo", { repoPath, remote, prune, taskId })),
	pullRepo: (repoPath: string, remote: string | null, branch: string | null, rebase: boolean | null, taskId: string | null) => typedError<string, AppError>(__TAURI_INVOKE("pull_repo", { repoPath, remote, branch, rebase, taskId })),
	pushRepo: (repoPath: string, remote: string | null, branch: string | null, setUpstream: boolean | null, force: boolean | null, taskId: string | null) => typedError<string, AppError>(__TAURI_INVOKE("push_repo", { repoPath, remote, branch, setUpstream, force, taskId })),
	cloneRepo: (url: string, targetDir: string, taskId: string | null) => typedError<string, AppError>(__TAURI_INVOKE("clone_repo", { url, targetDir, taskId })),
	cancelRemoteTask: (taskId: string) => typedError<null, AppError>(__TAURI_INVOKE("cancel_remote_task", { taskId })),
	setRepoPullRebase: (repoPath: string, rebase: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_repo_pull_rebase", { repoPath, rebase })),
	getStashes: (repoPath: string) => typedError<StashItem[], AppError>(__TAURI_INVOKE("get_stashes", { repoPath })),
	saveStash: (repoPath: string, message: string | null, includeUntracked: boolean | null) => typedError<string, AppError>(__TAURI_INVOKE("save_stash", { repoPath, message, includeUntracked })),
	applyStash: (repoPath: string, index: number) => typedError<null, AppError>(__TAURI_INVOKE("apply_stash", { repoPath, index })),
	popStash: (repoPath: string, index: number) => typedError<null, AppError>(__TAURI_INVOKE("pop_stash", { repoPath, index })),
	dropStash: (repoPath: string, index: number) => typedError<string, AppError>(__TAURI_INVOKE("drop_stash", { repoPath, index })),
	getRepoState: (repoPath: string) => typedError<RepoStateInfo, AppError>(__TAURI_INVOKE("get_repo_state", { repoPath })),
	mergeBranch: (repoPath: string, targetBranch: string, noFf: boolean | null) => typedError<MergeResult, AppError>(__TAURI_INVOKE("merge_branch", { repoPath, targetBranch, noFf })),
	rebaseBranch: (repoPath: string, upstreamBranch: string) => typedError<RebaseResult, AppError>(__TAURI_INVOKE("rebase_branch", { repoPath, upstreamBranch })),
	abortInProgress: (repoPath: string, operation: string) => typedError<null, AppError>(__TAURI_INVOKE("abort_in_progress", { repoPath, operation })),
	continueInProgress: (repoPath: string, operation: string) => typedError<null, AppError>(__TAURI_INVOKE("continue_in_progress", { repoPath, operation })),
	getConflictFileData: (repoPath: string, filePath: string) => typedError<ConflictFileData, AppError>(__TAURI_INVOKE("get_conflict_file_data", { repoPath, filePath })),
	resolveConflictFile: (repoPath: string, filePath: string, resolvedContent: string, autoStage: boolean | null) => typedError<null, AppError>(__TAURI_INVOKE("resolve_conflict_file", { repoPath, filePath, resolvedContent, autoStage })),
	undoCommit: (repoPath: string, undoToken: string) => typedError<null, string>(__TAURI_INVOKE("undo_commit", { repoPath, undoToken })),
	undoDeleteBranch: (repoPath: string, branchName: string, backupRef: string) => typedError<null, string>(__TAURI_INVOKE("undo_delete_branch", { repoPath, branchName, backupRef })),
	undoDropStash: (repoPath: string, receipt: string) => typedError<null, string>(__TAURI_INVOKE("undo_drop_stash", { repoPath, receipt })),
	getGitConfig: (repoPath: string | null) => typedError<GitConfigDto, AppError>(__TAURI_INVOKE("get_git_config", { repoPath })),
	setGitConfig: (repoPath: string | null, scope: ConfigScope, key: string, value: string) => typedError<null, AppError>(__TAURI_INVOKE("set_git_config", { repoPath, scope, key, value })),
	getTags: (repoPath: string) => typedError<TagItem[], AppError>(__TAURI_INVOKE("get_tags", { repoPath })).then((v) => ((v.status === "ok" ? { ...v, data: v.data.map(i=>({...i,timestamp_sec:i.timestamp_sec==null?i.timestamp_sec:i.timestamp_sec})) } : v) as typeof v)),
	createTag: (repoPath: string, name: string, targetCommit: string, message: string | null) => typedError<null, AppError>(__TAURI_INVOKE("create_tag", { repoPath, name, targetCommit, message })),
	deleteTag: (repoPath: string, name: string, deleteRemote: boolean | null) => typedError<null, AppError>(__TAURI_INVOKE("delete_tag", { repoPath, name, deleteRemote })),
	checkoutTag: (repoPath: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("checkout_tag", { repoPath, name })),
	pushTag: (repoPath: string, name: string, remoteName: string | null) => typedError<null, AppError>(__TAURI_INVOKE("push_tag", { repoPath, name, remoteName })),
	cherryPickCommit: (repoPath: string, commitId: string, autoCommit: boolean | null) => typedError<CommitActionResult, AppError>(__TAURI_INVOKE("cherry_pick_commit", { repoPath, commitId, autoCommit })),
	revertCommit: (repoPath: string, commitId: string, autoCommit: boolean | null) => typedError<CommitActionResult, AppError>(__TAURI_INVOKE("revert_commit", { repoPath, commitId, autoCommit })),
	getFileBlame: (repoPath: string, filePath: string, commitId: string | null) => typedError<FileBlameResult, AppError>(__TAURI_INVOKE("get_file_blame", { repoPath, filePath, commitId })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,lines:v.data.lines.map(i=>i)}) } : v) as typeof v)),
	getFileHistory: (repoPath: string, filePath: string, offset: number | null, limit: number | null) => typedError<FileHistoryResult, AppError>(__TAURI_INVOKE("get_file_history", { repoPath, filePath, offset, limit })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,commits:v.data.commits.map(i=>i)}) } : v) as typeof v)),
	getRemotes: (repoPath: string) => typedError<RemoteItem[], AppError>(__TAURI_INVOKE("get_remotes", { repoPath })),
	addRemote: (repoPath: string, name: string, url: string) => typedError<RemoteItem, AppError>(__TAURI_INVOKE("add_remote", { repoPath, name, url })),
	renameRemote: (repoPath: string, oldName: string, newName: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_remote", { repoPath, oldName, newName })),
	removeRemote: (repoPath: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_remote", { repoPath, name })),
	setRemoteUrl: (repoPath: string, name: string, fetchUrl: string, pushUrl: string | null) => typedError<null, AppError>(__TAURI_INVOKE("set_remote_url", { repoPath, name, fetchUrl, pushUrl })),
	pruneRemote: (repoPath: string, remote: string, taskId: string | null) => typedError<PruneResult, AppError>(__TAURI_INVOKE("prune_remote", { repoPath, remote, taskId })),
	getRebaseCommits: (repoPath: string, baseCommitId: string) => typedError<RebaseCommitItem[], AppError>(__TAURI_INVOKE("get_rebase_commits", { repoPath, baseCommitId })),
	executeInteractiveRebase: (repoPath: string, baseCommitId: string, steps: RebasePlanStep[], autoStash: boolean | null) => typedError<InteractiveRebaseResult, AppError>(__TAURI_INVOKE("execute_interactive_rebase", { repoPath, baseCommitId, steps, autoStash })),
	compareCommits: (repoPath: string, baseRev: string, targetRev: string, mode: CompareMode) => typedError<CompareSummary, AppError>(__TAURI_INVOKE("compare_commits", { repoPath, baseRev, targetRev, mode })),
	getCompareFileDiff: (repoPath: string, baseRev: string, targetRev: string, filePath: string, mode: CompareMode, ignoreWs: boolean | null) => typedError<FileDiffResult, AppError>(__TAURI_INVOKE("get_compare_file_diff", { repoPath, baseRev, targetRev, filePath, mode, ignoreWs })),
	getGithubRepoInfo: (repoPath: string) => typedError<GitHubRepoInfo, AppError>(__TAURI_INVOKE("get_github_repo_info", { repoPath })),
	getGithubToken: () => typedError<string | null, AppError>(__TAURI_INVOKE("get_github_token")),
	saveGithubToken: (token: string) => typedError<null, AppError>(__TAURI_INVOKE("save_github_token", { token })),
	removeGithubToken: () => typedError<null, AppError>(__TAURI_INVOKE("remove_github_token")),
	checkoutPullRequest: (repoPath: string, prNumber: number) => typedError<CheckoutPrResult, AppError>(__TAURI_INVOKE("checkout_pull_request", { repoPath, prNumber })),
};

/* Types */
export type AppError = { type: "Git"; message: string } | { type: "Io"; message: string } | { type: "NotFound"; message: string } | { type: "CommandFailed"; message: {
	code: number,
	stderr: string,
} } | { type: "InvalidOperation"; message: string };

export type BlameLine = {
	line_no: number,
	content: string,
	commit_id: string,
	short_id: string,
	summary: string,
	author_name: string,
	author_email: string,
	timestamp_sec: number,
	is_hunk_start: boolean,
};

export type BranchItem = {
	name: string,
	is_head: boolean,
	target_commit_id: string,
	upstream: string | null,
	ahead: number,
	behind: number,
};

export type BranchListResult = {
	current_branch: string | null,
	is_detached: boolean,
	local: BranchItem[],
	remote: BranchItem[],
	tags: string[],
};

export type CheckoutPrResult = {
	branch_name: string,
	message: string,
};

export type CommitActionResult = {
	success: boolean,
	status: string,
	new_commit_id: string | null,
	undo_token: string | null,
	output: string,
};

export type CommitChangedFile = {
	path: string,
	status: string,
	additions: number,
	deletions: number,
};

export type CommitDetails = CommitDetails_Serialize | CommitDetails_Deserialize;

export type CommitDetails_Deserialize = {
	undo_token?: string | null,
	id: string,
	full_message: string,
	author_name: string,
	author_email: string,
	author_timestamp_sec: number,
	parent_ids: string[],
	files: CommitChangedFile[],
	total_additions: number,
	total_deletions: number,
};

export type CommitDetails_Serialize = {
	undo_token?: string | null,
	id: string,
	full_message: string,
	author_name: string,
	author_email: string,
	author_timestamp_sec: number,
	parent_ids: string[],
	files: CommitChangedFile[],
	total_additions: number,
	total_deletions: number,
};

export type CommitGraphPage = {
	commits: GraphCommitNode[],
	has_more: boolean,
	total_count: number,
};

export type CompareCommitItem = {
	id: string,
	short_id: string,
	summary: string,
	author_name: string,
	author_email: string,
	timestamp: number,
	parent_ids: string[],
};

export type CompareFileItem = {
	path: string,
	old_path: string | null,
	status: string,
	additions: number,
	deletions: number,
	is_binary: boolean,
};

export type CompareMode = "MergeBase" | "Direct";

export type CompareSummary = {
	base_rev: string,
	target_rev: string,
	resolved_base_oid: string,
	resolved_target_oid: string,
	effective_base_oid: string,
	merge_base_oid: string | null,
	mode: CompareMode,
	ahead_count: number,
	behind_count: number,
	commits: CompareCommitItem[],
	files: CompareFileItem[],
	total_additions: number,
	total_deletions: number,
};

export type ConfigScope = "global" | "local";

export type ConflictFileData = {
	file_path: string,
	total_conflicts: number,
	hunks: ConflictHunk[],
};

export type ConflictHunk = {
	id: string,
	is_conflict: boolean,
	content: string | null,
	ours: string | null,
	theirs: string | null,
	base: string | null,
	ours_label: string | null,
	theirs_label: string | null,
};

export type DiffHunk = {
	header: string,
	old_start: number,
	old_lines: number,
	new_start: number,
	new_lines: number,
	lines: DiffLine[],
};

export type DiffLine = {
	line_type: string,
	content: string,
	old_lineno: number | null,
	new_lineno: number | null,
};

export type FileBlameResult = {
	file_path: string,
	commit_id: string | null,
	lines: BlameLine[],
	total_lines: number,
};

export type FileDiffResult = {
	file_path: string,
	status: string,
	hunks: DiffHunk[],
	additions: number,
	deletions: number,
};

export type FileHistoryItem = {
	commit_id: string,
	short_id: string,
	summary: string,
	author_name: string,
	author_email: string,
	timestamp_sec: number,
	change_type: string,
};

export type FileHistoryResult = {
	file_path: string,
	commits: FileHistoryItem[],
	has_more: boolean,
	total_count: number,
};

export type FileStatus = "Modified" | "New" | "Deleted" | "Renamed" | "Typechange" | "Conflicted";

export type GitConfigDto = {
	userName: string | null,
	userNameSource: ConfigScope | null,
	userEmail: string | null,
	userEmailSource: ConfigScope | null,
	defaultBranch: string | null,
	pullRebase: boolean | null,
	gpgSign: boolean | null,
	gpgKey: string | null,
	fetchPrune: boolean | null,
	rebaseAutostash: boolean | null,
};

export type GitHubRepoInfo = {
	is_github: boolean,
	owner: string | null,
	repo: string | null,
	default_branch: string | null,
};

export type GraphCommitNode = {
	id: string,
	short_id: string,
	summary: string,
	author_name: string,
	author_email: string,
	timestamp_sec: number,
	parent_ids: string[],
	col: number,
	color_index: number,
	lines: GraphEdge[],
	refs: RefBadge[],
};

export type GraphEdge = {
	from_col: number,
	to_col: number,
	edge_type: string,
	color_index: number,
};

export type InteractiveRebaseResult = {
	success: boolean,
	status: string,
	head_commit_id: string | null,
	undo_token: string | null,
	output: string,
};

export type MergeResult = {
	success: boolean,
	status: string,
	output: string,
};

export type PruneResult = {
	remote: string,
	pruned_branches: string[],
	message: string,
};

export type RebaseActionKind = "Pick" | "Reword" | "Squash" | "Fixup" | "Drop";

export type RebaseCommitItem = {
	id: string,
	short_id: string,
	summary: string,
	message: string,
	author_name: string,
	author_email: string,
	timestamp: number,
	parent_ids: string[],
};

export type RebasePlanStep = {
	commit_id: string,
	action: RebaseActionKind,
	new_message: string | null,
};

export type RebaseResult = {
	success: boolean,
	status: string,
	output: string,
};

export type RecentRepoEntry = {
	path: string,
	name: string,
	last_opened_at_ms: number,
};

export type RefBadge = {
	name: string,
	ref_type: string,
};

export type RemoteItem = {
	name: string,
	fetch_url: string | null,
	push_url: string | null,
	branch_count: number,
	is_default: boolean,
};

export type RepoChangedPayload = {
	repo_path: string,
	reason: string,
	timestamp_ms: number,
};

export type RepoHeadInfo = {
	branch_name: string | null,
	head_commit_id: string | null,
	is_detached: boolean,
	ahead: number,
	behind: number,
	upstream: string | null,
};

export type RepoStateInfo = {
	state: string,
	is_in_progress: boolean,
	head_name: string,
	target_name: string | null,
	conflict_count: number,
};

export type RepoStatusResult = {
	staged: StatusFileItem[],
	unstaged: StatusFileItem[],
	untracked: StatusFileItem[],
	conflicted: StatusFileItem[],
};

export type RepoSummary = {
	path: string,
	name: string,
	is_bare: boolean,
	head_branch: string | null,
	head_commit_id: string | null,
};

export type StashItem = {
	index: number,
	message: string,
	commit_id: string,
	created_at: number,
};

export type StatusFileItem = {
	path: string,
	status: FileStatus,
	is_staged: boolean,
	old_path: string | null,
};

export type SystemInfo = {
	os: string,
	arch: string,
	git_version: string,
	app_version: string,
};

export type TagItem = {
	name: string,
	target_commit_id: string,
	short_commit_id: string,
	commit_summary: string,
	is_annotated: boolean,
	message: string | null,
	tagger_name: string | null,
	tagger_email: string | null,
	timestamp_sec: number | null,
};

export type TaskProgressPayload = {
	task_id: string,
	progress_percent: number,
	status_text: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

